# src/tools/pytest_writer.py
from pathlib import Path
from .sandbox_tools import ensure_safe_path
from .file_tools import write_file


def generate_pytest_file(file_name: str, fixed_code: str, test_assertions: str, tests_folder: Path = Path("sandbox/tests")) -> Path:
    """
    Generates a in tests_folder which probably willbe Path('sandbpx/tests') for example pytest file.

    Args:
        file_name: original Python file name (e.g., "foo.py") passed with file_path.name
         when looping through the list of files in the folder.
        
        fixed_code: the code fixed by Fixer agent
        test_assertions: the test functions/assertions generated by Testeur agent
        tests_folder: folder to store the test file (sandbox/tests)

    Returns:
        Path to the generated test file
    """

    # Ensure test folder exists
    tests_folder = ensure_safe_path(tests_folder)
    tests_folder.mkdir(parents=True, exist_ok=True) '''if tests folder dont exist it will be created '''

    # Build test file name
    test_file_name = f"test_{file_name}" '''the name of the file that we are currently fixing + test_, 
     u pass it in the argument using file_path.name '''
    test_file_path = ensure_safe_path(tests_folder / test_file_name) "it return the path of the file if there is sandbox"

    # Combine fixed code + assertions
    test_file_content = f"{fixed_code}\n\n{test_assertions}"

    # Write to sandbox/tests/test_<file_name>.py
    write_file(test_file_path, test_file_content) """it writes and creates the test file with fixed code 
    and assertions generated by testeur"""

    return test_file_path



def run_pytest(test_file_path: Path) -> bool:
    """
    Run pytest on a given test file.
    
    Args:
        test_file_path: Path to the test file (sandbox/tests/test_<file>.py) 
        returned by the function above generate_pytest_file
    
    Returns:
        True if all tests pass, False if any fail.
    """
    safe_path = ensure_safe_path(test_file_path)

    # Run pytest quietly, capture output
    result = subprocess.run(
        ["pytest", str(safe_path), "--tb=short", "--disable-warnings"],
        cwd=safe_path.parent,
        capture_output=True,
        text=True
    )

    # Optional: print output for debugging
    print(result.stdout)
    print(result.stderr)

    return result.returncode == 0
    """  guys here is an example of the test file assertions 
    def test_add():
    assert add(2, 3) == 5
    assert add(1, 1) == 2
    this is gonna be given by the testeur agent , and the fixer is gonna give add(a,b) and both are 
    in the test file
    the pytest runs add(2,3) using the fixer add function , it comapres it to the assertion given by 
    testeur , it must be 5 , if it finds it different it returns this for example:
      def test_add():
>       assert add(2, 3) == 5
E       assert -1 == 5
E        +  where -1 = add(2, 3) , which means 

test_math_utils.py:4"""
